project:
  type: website

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    page-layout: full
    link-external-newwindow: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked

metadata-files: [nbdev.yml, sidebar.yml]