# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['extract_stat']

# %% ../nbs/00_core.ipynb 3
import importlib
import numpy as np
import pandas as pd

import statsmodels.api as sm
from linearmodels import PanelOLS

from .utils import *

# %% ../nbs/00_core.ipynb 6
def extract_stat(res, package: str=None, stat: str=None): 
    results_package = importlib.import_module(f"estout.{package}_results")
    return rgetattr(results_package,stat)(res)
