# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['extract_stat', 'model_results', 'to_df', 'to_tex']

# %% ../nbs/00_core.ipynb 3
import importlib
import numpy as np
import pandas as pd

import statsmodels.api as sm
from linearmodels import PanelOLS

from .utils import *

# %% ../nbs/00_core.ipynb 6
def extract_stat(res, package: str=None, stat: str=None): 
    results_package = importlib.import_module(f"estout.{package}_results")
    return rgetattr(results_package,stat)(res)

# %% ../nbs/00_core.ipynb 9
def model_results(res, # results object to extract stats from
                  add_stats: dict=None # stats to extract in addition to the default ones
                  ) -> dict:
    pass

# %% ../nbs/00_core.ipynb 11
def to_df(res_list,
          which_xvars
          ) -> pd.DataFrame: 
    pass
#like tabulate function

# %% ../nbs/00_core.ipynb 13
def to_tex(get_pdf=True, open_pdf=False):
    pass
